// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://clxdfnphvefjnzxgftzr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNseGRmbnBodmVmam56eGdmdHpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NTc5MjEsImV4cCI6MjA1OTEzMzkyMX0.nL4vON8FC5RPzVC-C_rngWTOWW3209iZUCo5Y25biOY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);